nelmio_api_doc:
    documentation:
        info:
            title: Happy
            description: I'm an imaginary friend. Imaginary! What's your excuse to exist ?!
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc.json$) # Accepts routes under /api except /api/doc
